version: '3'
services:

  app:
    image: dekribellyliu/captcha-webapp:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - app

networks:
  app: